version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - javac src/Main.java
      - mkdir out
      - cd src
      - jar cfe ../out/web.jar Main *.class
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - out/web.jar
    - appspec.yml
